alias stat='stat -x'
alias la='ls -a'
alias ll='ls -l'
alias l='ls -a -l -i'
alias li='ls -i'

alias Desktop='~/Desktop'
alias works='~/works'
alias Dropbox='~/Dropbox'
alias tmp='~/tmp'
alias github='~/github'